services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db/

  valkey:
    image: valkey/valkey:latest
    volumes:
      - valkey_data:/usr/local/etc/valkey

  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env

volumes:
  mongodb_data:
  valkey_data:
